import { plugin as shadcn } from '@shadcn/lint'
import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'

const eslintConfig = defineConfig([
    ...nextVitals,
    // @shadcn/lint design-system rules.
    // Docs: https://github.com/shadcn-ui/lint#rules
    // Precise rules are errors. High-volume rules are warnings until the
    // backlog is cleared; promote them to "error" once `pnpm lint` is clean.
    {
        files: ['**/*.{js,jsx,ts,tsx}'],
        plugins: { shadcn },
        settings: {
            shadcn: {
                note: 'Design tokens live in src/app/globals.css.',
            },
        },
        rules: {
            'shadcn/no-raw-colors': 'error',
            'shadcn/no-unknown-classes': [
                'error',
                // Vinyl player classes are defined in src/app/globals.css.
                {
                    allow: [
                        'not-prose',
                        'vinyl-button',
                        'vinyl-record',
                        'vinyl-label',
                        'vinyl-tonearm',
                    ],
                },
            ],
            'shadcn/require-static-classes': 'error',
            'shadcn/no-restyle': ['warn', { allow: ['layout'] }],
            'shadcn/no-arbitrary-values': 'warn',
            'shadcn/no-inline-styles': 'warn',
        },
    },
    // shadcn primitives and vendored magicui components own their styling.
    {
        files: ['src/components/ui/**', 'src/components/magicui/**'],
        rules: {
            'shadcn/no-restyle': 'off',
            'shadcn/no-arbitrary-values': 'off',
        },
    },
    // Brand marks (React, Python, Postgres, GitHub, ...) are defined by their
    // owners. Their colors are not ours to tokenize.
    {
        files: ['src/components/ui/svgs/**', 'src/components/icons.tsx'],
        rules: {
            'shadcn/no-raw-colors': 'off',
            'shadcn/no-inline-styles': 'off',
        },
    },
    // Satori renders OG images without a stylesheet, so inline styles are the
    // only styling mechanism available.
    {
        files: ['src/app/**/opengraph-image.tsx'],
        rules: { 'shadcn/no-inline-styles': 'off' },
    },
    // magicui animates through motion style values, which must stay inline.
    {
        files: ['src/components/magicui/**'],
        rules: { 'shadcn/no-inline-styles': 'off' },
    },
    // Primitives forward renamed className props and call cva variants; the
    // static-class check cannot follow those.
    {
        files: ['src/components/ui/**'],
        rules: { 'shadcn/require-static-classes': 'off' },
    },
    // Override default ignores of eslint-config-next.
    globalIgnores([
        // Default ignores of eslint-config-next:
        '.next/**',
        'out/**',
        'build/**',
        'next-env.d.ts',
        '.content-collections/**', // Generated by content-collections.
    ]),
])

export default eslintConfig
